# **Numpy**
Numpy is a powerful library for scientific computation in Python. Its main object is a multi-dimensional array of **numbers** and it provides fast routines for mathematical operations, sorting, selection, shape manipulation, linear algebra and statistical simulation. <br>
More on Numpy: https://www.w3schools.com/python/numpy/default.asp

## Why Numpy?

Let us try to write a code which multiplies the corresponding elements in 2 lists in native python

In [24]:
# multiply the corresponding elements in 2 lists
bar = [1,2,3]
foo = [4,5,6]
barfoo = []
for i in range(len(bar)):
    barfoo.append(bar[i]*foo[i])
print(barfoo)

[4, 10, 18]


The above example is very inefficient as the multiplications are done sequentially. Numpy does the multiplications in parallel at near C speeds.

In [25]:
import numpy as np
bar = np.array([1,2,3])
foo = np.array([4,5,6])
barfoo = bar*foo
print(barfoo)

[ 4 10 18]


Let us try to time both codes for 2 large arrays using Python built-in time library

In [26]:
#import libraries
from time import time
import numpy as np

bar = list(range(1,100000))
foo = list(range(1,100000))

In [28]:
#normal approach
barfoo = []
start = time()
for i in range(len(bar)):
    barfoo.append(bar[i]*foo[i])
end = time()
print('Elapsed time in case of Looping:',1000*(end-start),'ms')

#numpy approach
bar = np.array(bar)
foo = np.array(foo)
start = time()  
barfoo = bar*foo
end = time()
print('Elapsed time using NumPy:',1000*(end-start),'ms')

Elapsed time in case of Looping: 22.93705940246582 ms
Elapsed time using NumPy: 1.4324188232421875 ms


## **Array Creation & Manipulation**

In [13]:
import numpy as np
a = np.array([4,1,3]) 
print(a,type(a))

a = np.array([[1,2,3],[4,5,6]], dtype='float') #choose the data type
print(a,type(a)) 

[4 1 3] <class 'numpy.ndarray'>
[[1. 2. 3.]
 [4. 5. 6.]] <class 'numpy.ndarray'>


In [36]:
a = np.linspace(0,100, 10) #evenly spaced
print(a)

a = np.arange(0,100,10) #evenly spaced with a step size
print(a) 

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
[ 0 10 20 30 40 50 60 70 80 90]


In [37]:
a = np.zeros((3,5),dtype='int') #array of zeros
print(a)

a = np.ones((2,4),dtype='float') #array of ones
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [29]:
a = np.empty((1,4)) #array with uninitialized values
print(a)

a = np.eye(3) #matrix
print(a)

[[2.12199579e-314 1.02360935e-306 3.83394941e-321 1.61611199e-310]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### **Numpy arrays have 6 attributes:**


*   **shape** is the dimensions of the array.
*   **ndim** is the number of dimensions of the array.
*   **size** is the number of elements in the array.
*   **dtype** is the type of elements in the array
*   **itemsize** is the size of an element in the array in bytes
*   **data** is a buffer which contains the elements of the array. But, this attribute is rarely used as we access array elements using indexing



In [19]:
a = np.arange(2,12,1)
print(a)

print(a.shape)
print(a.ndim)
print(a.size) #number of elements in array
print(a.itemsize) #the memory usage of each element in bytes
print(a.dtype)
print(a.data[1])

[ 2  3  4  5  6  7  8  9 10 11]
(10,)
1
10
4
int32
3


**Indexing Numpy Arrays is so similar to MATLAB**

In [70]:
a = np.array([[4,3,1],[2,1,2],[4,7,3]])
'''
4 3 1 
2 1 2
4 7 3
'''
print(a[0,1])
print(a[0][1])

print(a[1,:])
print(a[:,0])

3
3
[2 1 2]
[4 2 4]


In [47]:
ix = np.array([1,1,0],dtype='bool')
print(a[:,ix]) # supports logical indexing (it comes in handy in plenty of situations)

[[4 3]
 [2 1]
 [4 7]]


**Arithmetic operators on arrays apply element-wise**

In [48]:
a = np.array([1,2,3])
b = np.array([2,4,6])
print(a-b)
print(a+b)
print(a*b)
print(a**b)
print(a/b)

[-1 -2 -3]
[3 6 9]
[ 2  8 18]
[  1  16 729]
[0.5 0.5 0.5]


**Arrays support many unary operations**

In [20]:
a = np.arange(0,11,2)
print(a)

[ 0  2  4  6  8 10]


In [21]:
print('Sum of array elements: ',a.sum())
print('Array maximum: ',a.max())
print('Array minimum: ',a.min())
print('Array mean: ',a.mean())

Sum of array elements:  30
Array maximum:  10
Array minimum:  0
Array mean:  5.0


**Numpy supports universal functions that are applied element-wise to array elements**

In [22]:
a = np.array([0, np.pi/2, np.pi])
print(np.exp(a))
print(np.sin(a))
print(np.cos(a))
print(np.sin(a)**2+np.cos(a)**2)

[ 1.          4.81047738 23.14069263]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[1. 1. 1.]


**Shape Manipulation**

*   **Reshape** function returns its argument with a modified shape
*   **Resize** function modifies the array itself



In [81]:
#reshape
a = np.arange(5,20,1)

print(a.reshape(3,5))
print(a.reshape(5,-1)) # using -1 in the shape tuple automatically calculates the other dimension
print(a) # The array 'a' hasn't changed after calling reshape

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [23]:
#resize
a = np.arange(5,20,1)
print(a.resize(4,5))
print(a) # The array 'a' changed after calling resize

None
[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [ 0  0  0  0  0]]


In [89]:
a = np.arange(5,20,1).reshape(3,5)
print(a)
print(a.T) #transpose the array a

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 5 10 15]
 [ 6 11 16]
 [ 7 12 17]
 [ 8 13 18]
 [ 9 14 19]]


In [93]:
a = np.arange(5,20,1).reshape(3,5)
print(a)
print(a.ravel()) #concatenate all the elements

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


**Splitting and Stacking arrays**


In [99]:
a = np.ones((2,5))
b = np.zeros((2,3))
c = np.hstack((a,b)) # horizontally stacks the two arrays => # of rows must match
print(c,c.shape)

[[1. 1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0.]] (2, 8)


In [100]:
d = np.vstack((c,-np.ones((2,8)))) # vertically stacks the two arrays => # of columns must match
print(d,d.shape)

[[ 1.  1.  1.  1.  1.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  0.  0.  0.]
 [-1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1.]] (4, 8)


In [103]:
c,x = np.vsplit(d,(2,)) # split the rows vertically after the 2nd row
print(c)
print(x)

[[1. 1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0.]]
[[-1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1.]]


In [104]:
a,b = np.hsplit(c,(5,)) # split the columns horizontally after the 5th column
print(a)
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


**Copying numpy arrays**

In [134]:
a = np.ones((2,3))
b = a # shallow copy
b[0,0]= 5
print(a)
print(b)

[[5. 1. 1.]
 [1. 1. 1.]]
[[5. 1. 1.]
 [1. 1. 1.]]


In [135]:
a = np.ones((2,3))
b = a.copy() # deep copy
b[0,0] = 0
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 1. 1.]
 [1. 1. 1.]]


# **Classes**
As we have discussed, *everything* is an object in Python. Objects are, as you may know, instantiations of *classes* and, as you may have already guessed, you can indeed define your own classes.
#### This section was prepared by Eng. Muhammad Al Aref

In [9]:
class MyClass:
      
    class_variable = [1, 2, 3]
    
    def __init__(self):
        print('I am the constructor!')
        self.variable = 'I am an object variable'
        self._variable = 'I am a private object variable'
    
    def my_method(self):
        print('I am a method!')
    
    def my_returning_method(self, something):
        return something
    
    def my_variable_returning_method(self):
        return self._variable
    
    def _my_private_method(self):
        print('I am a private method and I "should" not be called from outside the class')
        
    @classmethod
    #a class method "must" take the class as an argument and usually does smth related to the class
    def my_class_method(cls):
        print('I am a class method and I implicitly get my class as my first argument:', cls)
        
    @staticmethod
    #a static method is used for defining generic Python functions
    def my_static_method():
        print('I am a class method and I behave just like any normal method, just call me from my class!')

In [10]:
#class initialization
my_class_instance = MyClass()
print(my_class_instance)

#test methods
print(my_class_instance.my_method())

print(my_class_instance.my_returning_method('I am the something!'))

print(my_class_instance.my_variable_returning_method())

print(my_class_instance.variable)

my_class_instance._my_private_method()  # while you can, you "shouldn't" do that

print(my_class_instance._variable)   # again, you can but you shouldn't

print(MyClass.class_variable)

MyClass.my_class_method()             # you can it from my_class_instance as well, but... you shouldn't
MyClass.my_static_method()            # again, you can it from my_class_instance as well, but?

I am the constructor!
I am a method!
None
I am the something!
I am a private object variable
I am an object variable
I am a private method and I "should" not be called from outside the class
I am a private object variable
[1, 2, 3]
I am a class method and I implicitly get my class as my first argument: <class '__main__.MyClass'>
I am a class method and I behave just like any normal method, just call me from my class!


## Inheritance

A class can inherit from another class. In effect, that gives the *child* class all the functionality of the *parent* class. *Child* classes can *override* some of these functionalities if needed.

In [5]:
class MyOtherClass(MyClass):
    
    def my_method(self):
            print("I am overriding my parent's method")
        
    def my_brand_new_method(self):
        print("I am not inherited")

In [6]:
my_other_instance = MyOtherClass()
my_other_instance.my_method()
my_other_instance.my_brand_new_method()
print(my_other_instance.my_returning_method('I am the something!'))
print(my_other_instance.my_variable_returning_method())
print(my_other_instance.variable)
MyOtherClass.my_class_method()
MyOtherClass.my_static_method()

I am the constructor!
I am overriding my parent's method
I am not inherited
I am the something!
I am a private object variable
I am an object variable
I am a class method and I implicitly get my class as my first argument: <class '__main__.MyOtherClass'>
I am a class method and I behave just like any normal method, just call me from my class!
